### ISSUE TITLE
Connection Timeout during send

### ISSUE THREAD

**Issue by kennonb** [mdbraber/imapwatch#1]
Hi,

I know next to nothing about Python, so I apologize in advance. 😄 

I'm trying to figure this out so I can use it with OmniFocus. I have everything setup using Python 3.5.6. I also installed all the dependencies using PIP (as far as I can tell). However, when I launch the watcher, it looks like it's working, but it never actually sends the email. I replaced some personal email details below, but the rest is copy/paste from Terminal. I also swapped it back to the built-in Things action to see if it was something I modified, but that didn't seem to help either. 

This is in the log:

```
2018-05-23 16:56:33,282 imapwatch  [84851] [INFO    ] [@SaneLater ] Flagged item: Test Message
2018-05-23 16:56:33,283 imapwatch  [84851] [DEBUG   ] [Sender     ] Sending message now: kennon@xTest.xCom => add-to-things-xxxxxx@things.email: Test Message
2018-05-23 17:01:43,632 stderr     [84851] [INFO    ] [Sender     ] Exception in thread Sender:
2018-05-23 17:01:43,633 stderr     [84851] [INFO    ] [Sender     ] Traceback (most recent call last):
2018-05-23 17:01:43,633 stderr     [84851] [INFO    ] [Sender     ]   File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
2018-05-23 17:01:43,633 stderr     [84851] [INFO    ] [Sender     ]     self.run()
2018-05-23 17:01:43,634 stderr     [84851] [INFO    ] [Sender     ]   File "/Users/kennon/.imapwatch/lib/imapwatch/sender.py", line 40, in run
2018-05-23 17:01:43,635 stderr     [84851] [INFO    ] [Sender     ]     self.sender.send(self.to, self.subject, self.body)
2018-05-23 17:01:43,635 stderr     [84851] [INFO    ] [Sender     ]   File "/Users/kennon/.imapwatch/lib/imapwatch/sender.py", line 24, in send
2018-05-23 17:01:43,636 stderr     [84851] [INFO    ] [Sender     ]     s = smtplib.SMTP_SSL(self.server)
2018-05-23 17:01:43,636 stderr     [84851] [INFO    ] [Sender     ]   File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/smtplib.py", line 1031, in __init__
2018-05-23 17:01:43,636 stderr     [84851] [INFO    ] [Sender     ]     source_address)
2018-05-23 17:01:43,637 stderr     [84851] [INFO    ] [Sender     ]   File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/smtplib.py", line 251, in __init__
2018-05-23 17:01:43,637 stderr     [84851] [INFO    ] [Sender     ]     (code, msg) = self.connect(host, port)
2018-05-23 17:01:43,637 stderr     [84851] [INFO    ] [Sender     ]   File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/smtplib.py", line 336, in connect
2018-05-23 17:01:43,638 stderr     [84851] [INFO    ] [Sender     ]     self.sock = self._get_socket(host, port, self.timeout)
2018-05-23 17:01:43,638 stderr     [84851] [INFO    ] [Sender     ]   File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/smtplib.py", line 1037, in _get_socket
2018-05-23 17:01:43,639 stderr     [84851] [INFO    ] [Sender     ]     self.source_address)
2018-05-23 17:01:43,639 stderr     [84851] [INFO    ] [Sender     ]   File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 724, in create_connection
2018-05-23 17:01:43,639 stderr     [84851] [INFO    ] [Sender     ]     raise err
2018-05-23 17:01:43,640 stderr     [84851] [INFO    ] [Sender     ]   File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 713, in create_connection
2018-05-23 17:01:43,640 stderr     [84851] [INFO    ] [Sender     ]     sock.connect(sa)
2018-05-23 17:01:43,641 stderr     [84851] [INFO    ] [Sender     ] TimeoutError: [Errno 60] Operation timed out
```

I'm hoping it's something obvious that I'm missing, but just not sure where to look at this point.

Thanks for any help you can provide! 👍

**Comment by kennonb** [comment]
Ok, I'm going to close this. I'm using Office365, and looks like I have to use a slightly different setup with `smtplib`.

I changed line 24 in `sender.py` to:

```
s = smtplib.SMTP(self.server, 587)
```

And added, below `s.ehlo()`:

```
s.starttls()
```

That seems to have done the trick and it's all working now. I might try and mess with some of the formatting though as it's all jumbled together. But overall, this is great! 😄  Thanks for this.

**Comment by mdbraber** [comment]
Excellent - great it worked out!
